/*
 * HmSplitTextFileByLine v1.0.6.6
 *
 * Copyright (c) 2024 Akitsugu Komiyama
 * under the MIT License
 */

hidemaruversion "9.25.99";

setcompatiblemode 0x08000000; // マクロ内変数を他と共用しない。

jsmode "WebView2\\HmSplitTextFileByLine";

js {

    let linesPerChunk = 500; // 500行ごとにファイルを分割する

    hidemaru.postExecMacroFile( currentmacrodirectory() + "\\" + "HmSplitTextFileByLine.main.mac", linesPerChunk );
}

